### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by gurdiga** [thoughtbot/apprenticeship#22]
The [Welcome to apprentice.io!](https://github.com/thoughtbot/apprenticeship/blob/master/markdown/onboarding-packet.md) has a broken link in “How am I doing?” section:

https://github.com/thoughtbot/apprentice-goals

I have skimmed the repo list but couldn’t find anything that would seem to be close.

**Comment by seanculver** [comment]
I also would love to see that as well.

**Comment by cpytel** [comment]
Sorry, this links to a repo of past and current apprentice actual goals. I can't share that without getting permission from all of them, and I don't have that permission.
