### ISSUE TITLE
link to the onboarding packet is broken

### ISSUE THREAD

**Issue by ajwann** [thoughtbot/apprenticeship#34]
Hey guys, the link to the onboarding-packed.md file on your [apprenticeship page](https://thoughtbot.com/playbook/our-company/apprenticeship) currently points to:
https://github.com/thoughtbot/apprenticeship/blob/master/markdown/onboarding-packet.md
and returns a 404 error..

It looks like this link should point to:
https://github.com/thoughtbot/apprenticeship/blob/master/onboarding-packet.md

**Comment by croaky** [comment]
Thanks! Fixing now.
