### ISSUE TITLE
Dead link on onboarding-packet.md

### ISSUE THREAD

**Issue by benfurber** [thoughtbot/apprenticeship#38]
Hi there, 

In the 'How am I doing?' section, paragraph three links to a https://github.com/thoughtbot/apprentice-goals which has either been deleted, moved or is private. 

By doing a quick search for 'apprentice' on your profile, I couldn't find an obvious suggested alternative link.

**Comment by cpytel** [comment]
Thanks for the heads up. With no alternative to link, I’ve removed that paragraph.

Thanks again.
